USE [master]
GO

IF EXISTS
	(SELECT * FROM sys.databases
	 WHERE [name] = 'grocery_store')
  DROP DATABASE [grocery_store]
GO

CREATE DATABASE [grocery_store]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'grocery_store', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\grocery_store_Data' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'grocery_store_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\grocery_store_Log_File' , SIZE = 51200KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [grocery_store].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [grocery_store] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [grocery_store] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [grocery_store] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [grocery_store] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [grocery_store] SET ARITHABORT OFF 
GO

ALTER DATABASE [grocery_store] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [grocery_store] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [grocery_store] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [grocery_store] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [grocery_store] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [grocery_store] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [grocery_store] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [grocery_store] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [grocery_store] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [grocery_store] SET  DISABLE_BROKER 
GO

ALTER DATABASE [grocery_store] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [grocery_store] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [grocery_store] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [grocery_store] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [grocery_store] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [grocery_store] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [grocery_store] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [grocery_store] SET RECOVERY FULL 
GO

ALTER DATABASE [grocery_store] SET  MULTI_USER 
GO

ALTER DATABASE [grocery_store] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [grocery_store] SET DB_CHAINING OFF 
GO

ALTER DATABASE [grocery_store] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [grocery_store] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [grocery_store] SET DELAYED_DURABILITY = DISABLED 
GO

--ALTER DATABASE [grocery_store] SET QUERY_STORE = OFF
--GO

ALTER DATABASE [grocery_store] SET  READ_WRITE
GO
